# Generated by Django 5.1.3 on 2025-12-05 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnioLectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('activo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('nivel', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('nombres', models.CharField(max_length=200)),
                ('apellido_paterno', models.CharField(max_length=200)),
                ('apellido_materno', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('nombres', models.CharField(max_length=200)),
                ('apellido_paterno', models.CharField(max_length=200)),
                ('apellido_materno', models.CharField(max_length=200)),
                ('correo', models.EmailField(blank=True, max_length=200, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, max_length=250, null=True)),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('secretaria', 'Secretaria'), ('docente', 'Docente')], max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.curso')),
            ],
            options={
                'unique_together': {('nombre', 'curso')},
            },
        ),
        migrations.CreateModel(
            name='DocenteAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_lectivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Gestion.aniolectivo')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.asignatura')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.docente')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Gestion.especialidad'),
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_programa', models.CharField(choices=[('adultos', 'Personas adultas'), ('nna', 'Niños y adolescentes'), ('intensivo', 'Intensivo')], max_length=20)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('anio_lectivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Gestion.aniolectivo')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t1', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('t2', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('t3', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('supletorio', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.docenteasignacion')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.matricula')),
            ],
        ),
        migrations.CreateModel(
            name='Paralelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.curso')),
            ],
            options={
                'unique_together': {('curso', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='matricula',
            name='paralelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Gestion.paralelo'),
        ),
        migrations.AddField(
            model_name='docenteasignacion',
            name='paralelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.paralelo'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Gestion.sucursal'),
        ),
        migrations.AddField(
            model_name='curso',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Gestion.sucursal'),
        ),
        migrations.AddField(
            model_name='docente',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Gestion.usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together={('estudiante', 'paralelo', 'anio_lectivo')},
        ),
        migrations.AlterUniqueTogether(
            name='docenteasignacion',
            unique_together={('docente', 'asignatura', 'paralelo', 'anio_lectivo')},
        ),
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together={('nombre', 'especialidad', 'sucursal')},
        ),
    ]
