# Generated by Django 5.1.3 on 2026-01-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0003_alter_curso_nivel_alter_curso_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='estado_estudiante',
            field=models.CharField(blank=True, choices=[('MATRICULADO', 'Matriculado'), ('RENUNCIA', 'Renuncia voluntaria'), ('DESERTOR', 'Desertor')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='jornada',
            field=models.CharField(blank=True, choices=[('MATUTINA', 'Matutina'), ('VESPERTINA', 'Vespertina'), ('NOCTURNA', 'Nocturna')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matricula',
            name='temporalidad',
            field=models.CharField(blank=True, choices=[('INTENSIVA', 'Intensiva'), ('NO_INTENSIVA', 'No intensiva')], max_length=20, null=True),
        ),
    ]
