# Generated by Django 5.1.3 on 2026-01-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0004_matricula_estado_estudiante_matricula_jornada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='ubicacion',
            field=models.CharField(blank=True, choices=[('Costa', 'Costa'), ('Sierra', 'Sierra')], max_length=20, null=True),
        ),
    ]
