# Generated by Django 5.1.3 on 2026-01-21 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0005_alter_sucursal_ubicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoNotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t1_inicio', models.DateField(blank=True, null=True)),
                ('t1_fin', models.DateField(blank=True, null=True)),
                ('t2_inicio', models.DateField(blank=True, null=True)),
                ('t2_fin', models.DateField(blank=True, null=True)),
                ('t3_inicio', models.DateField(blank=True, null=True)),
                ('t3_fin', models.DateField(blank=True, null=True)),
                ('sup_inicio', models.DateField(blank=True, null=True)),
                ('sup_fin', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('anio_lectivo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='periodo_notas', to='Gestion.aniolectivo')),
            ],
            options={
                'verbose_name': 'Período de Notas',
                'verbose_name_plural': 'Períodos de Notas',
            },
        ),
        migrations.CreateModel(
            name='PermisoEdicionNotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo', models.CharField(choices=[('t1', 'T1'), ('t2', 'T2'), ('t3', 'T3'), ('supletorio', 'Supletorio')], max_length=20)),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_edicion', to='Gestion.docenteasignacion')),
                ('autorizado_por', models.ForeignKey(blank=True, limit_choices_to={'rol': 'secretaria'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permisos_otorgados', to='Gestion.usuario')),
                ('matricula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permisos_edicion', to='Gestion.matricula')),
            ],
            options={
                'verbose_name': 'Permiso de Edición de Notas',
                'verbose_name_plural': 'Permisos de Edición de Notas',
                'indexes': [models.Index(fields=['asignacion', 'campo', 'activo'], name='Gestion_per_asignac_9bd3e2_idx'), models.Index(fields=['matricula', 'campo', 'activo'], name='Gestion_per_matricu_1e0640_idx')],
            },
        ),
    ]
