# Generated by Django 5.1.3 on 2026-01-22 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0006_periodonotas_permisoedicionnotas'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together={('estudiante', 'anio_lectivo')},
        ),
    ]
