# Generated by Django 5.1.3 on 2026-01-24 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0007_alter_matricula_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodonotas',
            options={},
        ),
    ]
