# Generated by Django 5.1.3 on 2026-01-24 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0008_alter_periodonotas_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='orden',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promedio_final', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('resultado', models.CharField(choices=[('APROBADO', 'Aprobado'), ('REPROBADO', 'Reprobado'), ('RETIRADO', 'Retirado')], max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('anio_lectivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Gestion.aniolectivo')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Gestion.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.estudiante')),
            ],
            options={
                'unique_together': {('estudiante', 'anio_lectivo')},
            },
        ),
    ]
