# Generated by Django 5.1.3 on 2026-01-25 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0009_curso_orden_promocion'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='matricula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promocion_generada', to='Gestion.matricula'),
        ),
        migrations.AddField(
            model_name='promocion',
            name='observacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='promocion',
            index=models.Index(fields=['estudiante', 'anio_lectivo'], name='Gestion_pro_estudia_2f88e5_idx'),
        ),
        migrations.AddIndex(
            model_name='promocion',
            index=models.Index(fields=['estudiante', 'resultado'], name='Gestion_pro_estudia_69dfc9_idx'),
        ),
        migrations.AddIndex(
            model_name='promocion',
            index=models.Index(fields=['curso'], name='Gestion_pro_curso_i_6c098a_idx'),
        ),
    ]
