# Generated by Django 5.1.3 on 2026-01-25 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0010_promocion_matricula_promocion_observacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='comportamiento',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='PromocionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura_nombre', models.CharField(max_length=150)),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=4)),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Gestion.promocion')),
            ],
            options={
                'ordering': ['asignatura_nombre'],
                'unique_together': {('promocion', 'asignatura_nombre')},
            },
        ),
    ]
