# Generated by Django 5.1.3 on 2026-02-20 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0011_promocion_comportamiento_promociondetalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='orden',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
