# Generated by Django 5.1.3 on 2026-03-10 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0012_alter_curso_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='etnia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='lgbti',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='nacionalidad_indigena',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='porcentaje_discapacidad',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='posee_discapacidad',
            field=models.CharField(blank=True, choices=[('SI', 'Sí'), ('NO', 'No')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='sexo',
            field=models.CharField(blank=True, choices=[('HOMBRE', 'Hombre'), ('MUJER', 'Mujer')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='tipo_discapacidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='tipo_documento',
            field=models.CharField(choices=[('CEDULA', 'Cédula')], default='CEDULA', max_length=20),
        ),
    ]
