# Generated by Django 5.1.3 on 2026-03-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0013_estudiante_etnia_estudiante_lgbti_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matricula',
            name='tipo_programa',
        ),
        migrations.AddField(
            model_name='matricula',
            name='oferta_educativa',
            field=models.CharField(choices=[('JOVENES_ADULTOS', 'PARA PERSONAS JÓVENES, ADULTAS Y ADULTAS MAYORES CON ESCOLARIDAD INCONCLUSA'), ('NNA_ESCOLARIDAD_INCONCLUSA', 'PARA NIÑAS, NIÑOS Y ADOLESCENTES EN EDAD ESCOLAR CON ESCOLARIDAD INCONCLUSA')], default='adultos', max_length=40),
            preserve_default=False,
        ),
    ]
