# Generated by Django 5.1.3 on 2026-03-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0014_remove_matricula_tipo_programa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='canton',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='parroquia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
