# Generated by Django 5.1.3 on 2026-03-11 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0015_usuario_canton_usuario_parroquia_usuario_provincia'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='canton',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='parroquia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='HistorialAcademicoIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion_procedencia', models.CharField(blank=True, max_length=200, null=True)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('curso_aprobado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Gestion.curso')),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historial_ingreso', to='Gestion.estudiante')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
