# Generated by Django 5.1.3 on 2026-03-12 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0016_estudiante_canton_estudiante_parroquia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='etnia',
            field=models.CharField(blank=True, choices=[('INDIGENA', 'Indígena'), ('MESTIZA', 'Mestiza'), ('NEGRA', 'Negra'), ('BLANCA', 'Blanca'), ('MONTUBIA', 'Montubia')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nacionalidad_indigena',
            field=models.CharField(blank=True, choices=[('ACHUAR', 'Achuar'), ('AI_KOFAN', 'Ai Kofan'), ('AWA_KWAIKER', 'Awá-Kwaiker'), ('CHACHI', 'Chachi'), ('EPERA', 'Épera'), ('KICHWA', 'Kichwa'), ('SECOYA', 'Secoya'), ('SHIWIAR', 'Shiwiar'), ('SHUAR', 'Shuar'), ('SIONA', 'Siona'), ('TSACHILA', 'Tsáchila'), ('WAORANI', 'Waorani'), ('ZAPARA', 'Zápara'), ('OTRA_NACIONALIDAD', 'Otra Nacionalidad')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='tipo_discapacidad',
            field=models.CharField(blank=True, choices=[('FISICA', 'Física'), ('INTELECTUAL', 'Intelectual'), ('AUDITIVA', 'Auditiva'), ('VISUAL', 'Visual'), ('PSICOSOCIAL', 'Psicosocial'), ('LENGUAJE', 'Lenguaje')], max_length=20, null=True),
        ),
    ]
