# Generated by Django 5.1.3 on 2026-03-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0017_alter_estudiante_etnia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='tipo_documento',
            field=models.CharField(choices=[('CEDULA', 'Cédula'), ('PASAPORTE', 'Pasaporte'), ('DNI', 'Documento extranjero')], default='CEDULA', max_length=20),
        ),
    ]
