# Generated by Django 5.1.3 on 2026-03-26 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0018_alter_estudiante_tipo_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorParalelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_lectivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Gestion.aniolectivo')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.docente')),
                ('paralelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.paralelo')),
            ],
            options={
                'unique_together': {('paralelo', 'anio_lectivo')},
            },
        ),
    ]
