# Generated by Django 5.1.3 on 2026-03-26 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0019_tutorparalelo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tutorparalelo',
            unique_together={('docente', 'anio_lectivo'), ('paralelo', 'anio_lectivo')},
        ),
    ]
