# Generated by Django 5.1.3 on 2026-03-26 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0020_alter_tutorparalelo_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tutorparalelo',
            unique_together={('paralelo', 'anio_lectivo')},
        ),
    ]
