# Generated by Django 5.1.3 on 2026-03-26 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0021_alter_tutorparalelo_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tutorparalelo',
            unique_together={('docente', 'anio_lectivo'), ('paralelo', 'anio_lectivo')},
        ),
    ]
